# Generated by Django 3.2.3 on 2021-06-10 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baracuda_Service', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Baracuda_Service.category'),
            preserve_default=False,
        ),
    ]
