# Generated by Django 3.2.3 on 2021-07-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baracuda_Service', '0003_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Category',
            new_name='category',
        ),
    ]
