# Generated by Django 3.2.3 on 2021-07-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baracuda_Service', '0005_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
